"use client";
import {useState,useEffect,useRef,type PointerEvent} from "react";
import {Code2,Layers3,Database,ExternalLink} from "lucide-react";
import ParticleScene from "./particle-scene";
import type {Portfolio} from "./portfolio-data";
function tilt(e:PointerEvent<HTMLElement>){if(e.pointerType!=="mouse"||matchMedia("(prefers-reduced-motion: reduce)").matches)return;const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;e.currentTarget.style.setProperty("--rx",((.5-y)*5)+"deg");e.currentTarget.style.setProperty("--ry",((x-.5)*5)+"deg");e.currentTarget.style.setProperty("--mx",x*100+"%");e.currentTarget.style.setProperty("--my",y*100+"%");}
function resetTilt(e:PointerEvent<HTMLElement>){e.currentTarget.style.setProperty("--rx","0deg");e.currentTarget.style.setProperty("--ry","0deg");}
export default function PortfolioView({data}:{data:Portfolio}){
const [filter,setFilter]=useState("All"),progress=useRef<HTMLDivElement>(null);
useEffect(()=>{const update=()=>{const total=document.documentElement.scrollHeight-innerHeight;if(progress.current)progress.current.style.transform="scaleX("+(total>0?scrollY/total:0)+")";};window.addEventListener("scroll",update,{passive:true});update();return()=>window.removeEventListener("scroll",update);},[]);
return <><div className="scroll-progress" ref={progress}/><header className="nav"><a className="brand" href="/" aria-label={data.name+" home"}>p<span>.</span></a><nav><a href="#work">Work</a><a href="#about">About</a><a href="#connect" className="nav-contact">Let's connect</a></nav></header>
<main id="top"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="tiny-cross">✳</span> {data.role} <span className="hero-edition">PORTFOLIO / {new Date().getFullYear()}</span></div><h1 className="hero-name">{data.name}</h1><p className="hero-manifesto">{data.headline} <span>{data.subheadline}</span></p><p className="intro">{data.intro}</p><div className="actions"><a className="primary" href="#work">Explore my work</a><a className="textlink" href={data.github} target="_blank" rel="noreferrer"><Code2 size={18}/> GitHub</a></div><div className="hero-note"><span>01 — EXPLORE</span><span>Code. Curiosity. Possibility.</span></div></div><ParticleScene/></section>
<div className="specialties">{[[Code2,"Machine learning"],[Layers3,"Computer vision"],[Database,"Backend & cloud"]].map(([Icon,title]:any)=><span key={title}><Icon size={19}/>{title}</span>)}<span className="specialty-end">FROM EXPERIMENTS TO APPLICATIONS</span></div>
<section id="work" className="section"><div className="sectionhead"><div><div className="eyebrow">01 / SELECTED WORK</div><h2>Ideas, built<br/><span className="soft-text">into reality.</span></h2></div><p>A selection across intelligent systems,<br/>explainability, and application development.</p></div><div className="filters" role="group" aria-label="Filter projects">{["All","Machine learning","Computer vision","Cloud & backend"].map(c=><button key={c} className={filter===c?"active":""} onClick={()=>setFilter(c)} aria-pressed={filter===c}>{c}</button>)}</div><div className="projects">{data.projects.filter(p=>filter==="All"||p.category===filter).map((p,i)=><article onPointerMove={tilt} onPointerLeave={resetTilt} className={"project "+(p.id==="finance"?"featured":"")} key={p.id}>{p.id==="finance"&&<div className="projectvisual"><div className="plotlabel">V4FINBENCH / MODEL EVALUATION</div><div className="plot-frame"><img src="/model-comparison.png" alt="V4FinBench model comparison chart from the project results"/></div><div className="visual-bottom"><span>RESEARCH IN PRACTICE</span><span>FIG. 01</span></div></div>}<div className="projectbody"><div className="projecttop"><span>{p.category}</span><span>{String(i+1).padStart(2,"0")}</span></div><h3>{p.title}</h3><p>{p.description}</p>{(p.problem||p.approach||p.contribution)&&<details className="project-story"><summary>Problem, approach &amp; my contribution</summary><dl>{p.problem&&<><dt>The problem</dt><dd>{p.problem}</dd></>}{p.approach&&<><dt>The approach</dt><dd>{p.approach}</dd></>}{p.contribution&&<><dt>My contribution</dt><dd>{p.contribution}</dd></>}</dl></details>}{p.reports.length>0&&<div className="project-reports"><span>PROJECT REPORTS</span>{p.reports.map(r=><a key={r.url+r.label} href={r.url} target="_blank" rel="noreferrer"><span className="pdf-badge">PDF</span>{r.label}<ExternalLink size={13}/></a>)}</div>}<div className="tags">{p.technologies.split(",").filter(Boolean).map(t=><span key={t}>{t.trim()}</span>)}</div><a href={p.url} target="_blank" rel="noreferrer">Explore repository <ExternalLink size={15}/></a></div></article>)}</div>{data.projects.filter(p=>filter==="All"||p.category===filter).length===0&&<p>No projects in this category yet.</p>}</section>
<section id="about" className="about section"><div><div className="eyebrow">02 / THE PERSON BEHIND THE CODE</div><h2>Always a student.<br/><span className="soft-text">Always building.</span></h2><p>{data.about}</p><div className="education"><span>EDUCATION</span><strong>{data.education}</strong></div></div><div className="toolbox"><div className="eyebrow">MY TOOLBOX</div><h3>Tools I work with.</h3><div className="skills">{data.skills.split(",").filter(Boolean).map(s=><span key={s}>{s.trim()}</span>)}</div><p>Applied across the projects above, from experimentation to deployment.</p></div></section>
{data.internshipCompany&&<section className="experience section"><div><div className="eyebrow">03 / PROFESSIONAL EXPERIENCE</div><h2>Learning beyond<br/><span className="soft-text">the classroom.</span></h2></div><article><div className="experience-date">{data.internshipDates}</div><h3>{data.internshipRole}</h3><strong>{data.internshipCompany}</strong><p>{data.internshipDescription}</p>{data.internshipCertificate&&<a href={data.internshipCertificate} target="_blank" rel="noreferrer"><span className="pdf-badge">PDF</span>View completion certificate <ExternalLink size={14}/></a>}</article></section>}<section id="connect" className="connect"><div className="eyebrow">04 / LET'S CONNECT</div><h2>Next great idea?<br/><span>Let's talk.</span></h2><p>Explore my code, follow my learning journey,<br/>or connect about a project.</p><div className="actions"><a className="primary" href={data.github} target="_blank" rel="noreferrer">Find me on GitHub</a>{data.email&&<a className="textlink" href={"mailto:"+data.email}>Email me</a>}</div><div className="connect-symbol" aria-hidden="true">✳</div></section></main>
<footer><span>© {new Date().getFullYear()} {data.name} · Built with curiosity.</span><a href="https://github.com/Pavan-amikula/pavan-amikula.github.io/edit/main/content.json" target="_blank" rel="noreferrer">Edit portfolio</a><a href="#top">Back to top</a></footer></>}


